### ISSUE TITLE
Slashes stripped from homepage URLs

### ISSUE THREAD

**Issue by gbp** [mysociety/wdtk_authorities_list#3]
Looks like there is an issue with the homepage URLs in this dataset. @ajparsons do we need to include `/` in this list of characters?

https://github.com/mysociety/wdtk_authorities_list/blob/eac3c154a734277fe0677d9b77d7afdcc63784d9/src/wdtk_authorities_list/build.py#L27-L49

**Comment by ajparsons** [comment]
Should be fixed!
